name: Cloudflared
version: 5.3.8
breaking_versions:
- 5.3.7
slug: cloudflared
description: Use Cloudflare’s DNS-over-HTTPS (DoH) service to forward DNS queries.
url: https://github.com/rpruden/ha-addons-cloudflared/
codenotary: dev@rpruden.tech
startup: services
init: false
hassio_api: true
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- homeassistant_config
options:
  # Enable the DNS-over-HTTPS (DoH) proxy mode
  use_builtin_proxy: true
  # List of upstream DNS servers to use via DoH
  upstream_dns_servers:
    - https://1.1.1.1/dns-query  # Cloudflare DoH
    - https://1.0.0.1/dns-query  # Cloudflare secondary DoH
  # Port to listen on for DNS requests
  listen_port: 5053
  log_level: debug
  tunnel_token: ""
  external_hostname: ""
  additional_hosts: []
  catch_all_service: ""
  nginx_proxy_manager: false
ports:
  5053/tcp: 5053
schema:
  use_builtin_proxy: bool?
  upstream_dns_servers:
    - str
  listen_port: int?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/brenner-tobias/cloudflared/{arch}
